<?php

namespace Tests;

 use Phone\Constant;
 use Phone\Operator;
 use PHPUnit\Framework\TestCase;

 class OperatorTest extends TestCase {
     /**
      * @var Operator
      */
     private $operator;

     protected function setUp()/* The :void return type declaration that should be here would cause a BC issue */
     {
         parent::setUp(); // TODO: Change the autogenerated stub
         $this->operator = new Operator();
     }

     /**
      * @test
      */
     public function verifyOrange()
     {
        $this->assertEquals(Constant::ORANGE, $this->operator->getOperator('237691131446'));
        $this->assertEquals(Constant::ORANGE, $this->operator->getOperator('237696706283'));
     }

     /**
      * @test
      */
     public function verifyMtn()
     {
         $this->assertEquals(Constant::MTN, $this->operator->getOperator('237678986466'));
     }

     /**
      * @test
      */
     public function verifyNexttel()
     {
         $this->assertEquals(Constant::NEXTTEL, $this->operator->getOperator('237665589240'));
     }

     /**
      * @test
      */
     public function verifyTelecel()
     {
         $this->assertEquals(Constant::TELECEL, $this->operator->getOperator('23675875050'));
     }
 }